[package]
name = "matchmaker"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
async-std = "1.9"
rand = "0.5.0"
byteorder = "1.4"
itertools = "0.10"